### ISSUE TITLE
Better documentation, including examples

### ISSUE THREAD

**Issue by gitet** [CiscoDevNet/ansible-nd#38]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please create documentation and examples that demonstrate how to use this collection.

It would be immensely helpful to have proper documentation for all

* modules
* roles 
* plugins

As it is right now, potential users of this collection will have to dig into the codebase in order to find out how make use of it. This is not optimal.

Many users are still taking their baby steps with ansible and may not have the capacity or skills needed in order to approach it in this way.

### New or Affected Module(s):

* N/A

### ND version and ND Platform

* N/A

### APIC version and APIC Platform for Site related features

* N/A

### Collection versions

* cisco.nd 0.2.0

### References

* #0000

**Comment by lhercot** [comment]
Hi @gitet, the new Ansible Galaxy now displays the documentation properly and can be accessed here for this collection: https://galaxy.ansible.com/ui/repo/published/cisco/nd/docs/

Let me know if this solves your issue or if you had something else in mind.

**Comment by gitet** [comment]
Hi @lhercot  - this was very much in line with what we were looking for - thanks and keep at it! Documentation rules!
