### ISSUE TITLE
Backup to remote location.

### ISSUE THREAD

**Issue by RonaldBlom** [CiscoDevNet/ansible-nd#5]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

for cimc, mso, apic we are able to create backup using automation, but the only part of our ACI environment is Nexus Dashboard, which is pretty "old fashioned" to create a backup. Hope there is a possibility to get more modules.

### New or Affected Module(s):

* nd_backup

### ND version and ND Platform

* V 2.0.2h and Physical

### APIC version and APIC Platform for Site related features

* V 4.2.7l and on-prem

### Collection versions

* cisco.nd 0.1.0

### References

* #0000

**Comment by gitet** [comment]
This repo is just yet another example of Cisco not taking their customers seriously. We need tools that will enable users to start automating without having to build things from scratch. Having a feature complete ansible collection would be nice.
